export { default as Hero } from './Hero';
export { default as AboutTop } from './AboutTop';
export { default as Features } from './Features';
export { default as Pricings } from './Pricings';
export { default as Integrations } from './Integrations';
export { default as Categories } from './Categories';
export { default as Advantages } from './Advantages';
export { default as Solutions } from './Solutions';
export { default as Reviews } from './Reviews';